In [1]:
import numpy as np

In [31]:
a = np.arange(start= 10, stop= 25, step= 1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
b= np.reshape(a, (5,3), order= 'F')

In [25]:
b


array([[10, 15, 20],
       [11, 16, 21],
       [12, 17, 22],
       [13, 18, 23],
       [14, 19, 24]])

In [13]:
c = a.resize((5,3))
c

In [15]:
print(c)

None


In [16]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [18]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
a.resize((5,3))

In [20]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [26]:
a.shape

(15,)

In [27]:
b.shape

(5, 3)

In [28]:
b.size

15

In [30]:
a.resize((5, 3))

In [35]:
c = np.resize(a, (5,4))

In [36]:
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 10],
       [11, 12, 13, 14]])

In [37]:
c.size

20

In [38]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
a.resize((5, 4), refcheck= False)

In [42]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24,  0],
       [ 0,  0,  0,  0]])

In [43]:
a.flatten()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,  0,  0,
        0,  0,  0])

In [44]:
a.flatten(order='F')

array([10, 14, 18, 22,  0, 11, 15, 19, 23,  0, 12, 16, 20, 24,  0, 13, 17,
       21,  0,  0])

In [45]:
a.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,  0,  0,
        0,  0,  0])

In [46]:
x = np.arange(27).reshape((3,3,3))

In [47]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [49]:
x.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [50]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
y = np.arange(12)[: : -1]
y

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [55]:
xy = np.arange(12).reshape((3, 4))
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
xy[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [58]:
y

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [59]:
y[1:6]

array([10,  9,  8,  7,  6])

In [60]:
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
xy.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
np.ravel(xy)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [64]:
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.transpose(xy)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [66]:
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
xy.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [75]:
ss = np.arange(1, 25).reshape(2, 3, 4)
ss

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [76]:
ss.transpose()

array([[[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]],

       [[ 4, 16],
        [ 8, 20],
        [12, 24]]])

In [77]:
ss.shape

(2, 3, 4)

In [78]:
ss.transpose().shape

(4, 3, 2)

In [80]:
ss.transpose((1,2,0)).shape

(3, 4, 2)

In [81]:
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
xy.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [85]:
xy.swapaxes(1, 0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [86]:
xy.swapaxes(0, 1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [98]:
a = np.arange(10).reshape(5, 2)
b = np.arange(11, 21).reshape(5, 2)

In [99]:
c = np.concatenate((a, b), axis= 1)

In [93]:
c

array([[ 0,  1, 11, 12],
       [ 2,  3, 13, 14],
       [ 4,  5, 15, 16],
       [ 6,  7, 17, 18],
       [ 8,  9, 19, 20]])

In [103]:
cc = np.random.rand(5, 4)
cc

array([[0.50141675, 0.91466521, 0.06978648, 0.68967067],
       [0.91479816, 0.83531672, 0.01129597, 0.53113022],
       [0.91548752, 0.63812219, 0.7052734 , 0.37835384],
       [0.00489345, 0.49679886, 0.64353842, 0.07960397],
       [0.68978249, 0.63980959, 0.42972686, 0.46498939]])

In [102]:
cc = np.concatenate((a, b), axis= 1)
cc

array([[ 0,  1, 11, 12],
       [ 2,  3, 13, 14],
       [ 4,  5, 15, 16],
       [ 6,  7, 17, 18],
       [ 8,  9, 19, 20]])

In [104]:
np.concatenate((a, b), axis= 1, out= cc)

array([[ 0.,  1., 11., 12.],
       [ 2.,  3., 13., 14.],
       [ 4.,  5., 15., 16.],
       [ 6.,  7., 17., 18.],
       [ 8.,  9., 19., 20.]])

In [105]:
cc

array([[ 0.,  1., 11., 12.],
       [ 2.,  3., 13., 14.],
       [ 4.,  5., 15., 16.],
       [ 6.,  7., 17., 18.],
       [ 8.,  9., 19., 20.]])

In [115]:
i = np.random.rand(4, 7)
j = np.random.rand(2, 4)

In [116]:
k = np.concatenate((i, j.transpose()), axis= 1)
k

array([[0.83659222, 0.81596829, 0.58215015, 0.94162663, 0.55261292,
        0.52231009, 0.28293592, 0.19682022, 0.12737725],
       [0.56537012, 0.98439948, 0.58039544, 0.9753304 , 0.69696432,
        0.58343918, 0.60853396, 0.08322587, 0.00880892],
       [0.67565748, 0.23358047, 0.96907174, 0.25298892, 0.11751795,
        0.96660028, 0.69156212, 0.26123596, 0.76789917],
       [0.02650898, 0.08484398, 0.24449175, 0.5317742 , 0.83321223,
        0.10391351, 0.63885565, 0.30876284, 0.15378955]])

In [117]:
a = np.random.rand(2, 3)
b = np.random.rand(4, 3)

In [118]:
c = np.concatenate((a, b), axis= 0)

In [119]:
c

array([[0.75652368, 0.27329391, 0.61013367],
       [0.09205149, 0.2683582 , 0.74941902],
       [0.54794585, 0.89508398, 0.79159825],
       [0.50032276, 0.44012164, 0.57724429],
       [0.89598275, 0.03884808, 0.61103281],
       [0.45801398, 0.50231508, 0.06591158]])

In [120]:
d = np.vstack((a, b))
d

array([[0.75652368, 0.27329391, 0.61013367],
       [0.09205149, 0.2683582 , 0.74941902],
       [0.54794585, 0.89508398, 0.79159825],
       [0.50032276, 0.44012164, 0.57724429],
       [0.89598275, 0.03884808, 0.61103281],
       [0.45801398, 0.50231508, 0.06591158]])

In [121]:
a = np.array([[1,2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [122]:
b = np.array([[5, 6],[7, 8]])
b

array([[5, 6],
       [7, 8]])

In [123]:
a*b

array([[ 5, 12],
       [21, 32]])

In [124]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [125]:
np.add(a, b)

array([[ 6,  8],
       [10, 12]])

In [126]:
a+b

array([[ 6,  8],
       [10, 12]])

In [127]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [128]:
m = np.matrix([[10, 11], [12, 13]])
m

matrix([[10, 11],
        [12, 13]])

In [129]:
type(m)

numpy.matrix

In [130]:
type(a)

numpy.ndarray

In [131]:
m**2

matrix([[232, 253],
        [276, 301]])

In [132]:
np.dot(m, m)

matrix([[232, 253],
        [276, 301]])

In [133]:
m = np.matrix([[1, 2], [3, 4]])
n = np.matrix([[5, 6], [7, 8]])

In [134]:
m * n

matrix([[19, 22],
        [43, 50]])

In [136]:
a[1,1] = 20

In [137]:
a

array([[ 1,  2],
       [ 3, 20]])

In [140]:
m[1, 1] = 50

In [141]:
m

matrix([[ 1,  2],
        [ 3, 50]])

In [142]:
p = np.matrix('1, 2; 3, 4')
p

matrix([[1, 2],
        [3, 4]])

In [143]:
type(p)

numpy.matrix

In [144]:
a

array([[ 1,  2],
       [ 3, 20]])

In [145]:
p

matrix([[1, 2],
        [3, 4]])

In [146]:
a.T

array([[ 1,  3],
       [ 2, 20]])

In [147]:
p.T

matrix([[1, 3],
        [2, 4]])

In [148]:
a

array([[ 1,  2],
       [ 3, 20]])

In [149]:
np.linalg.det(a)

14.000000000000004

In [150]:
np.linalg.inv(a)

array([[ 1.42857143, -0.14285714],
       [-0.21428571,  0.07142857]])

In [151]:
a

array([[ 1,  2],
       [ 3, 20]])

In [152]:
np.dot(a, a)

array([[  7,  42],
       [ 63, 406]])

In [153]:
np.dot(a.T, a)

array([[ 10,  62],
       [ 62, 404]])

In [154]:
b

array([[5, 6],
       [7, 8]])

In [155]:
np.dot(b, b)

array([[ 67,  78],
       [ 91, 106]])

In [156]:
np.dot(b.transpose(), b)

array([[ 74,  86],
       [ 86, 100]])

In [157]:
r =np.array([[1], [2], [3]])

In [158]:
r

array([[1],
       [2],
       [3]])

In [159]:
r.shape

(3, 1)

In [160]:
d = r.transpose()

In [161]:
d

array([[1, 2, 3]])

In [162]:
u = np.dot(r.T, r)

In [163]:
u

array([[14]])

In [164]:
t = np.dot(r, r)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [165]:
r**2

array([[1],
       [4],
       [9]], dtype=int32)

In [166]:
k = np.matrix('1; 2; 3')
k

matrix([[1],
        [2],
        [3]])

In [167]:
k**2

LinAlgError: Last 2 dimensions of the array must be square

In [168]:
np.dot(k.T, k)

matrix([[14]])

In [169]:
r

array([[1],
       [2],
       [3]])

In [170]:
r.T

array([[1, 2, 3]])

In [171]:
m = np.array([[1, 2,3], [3, 4, 5], [6,7,8]])
m

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
m_inv = np.linalg.inv(m)

In [176]:
m_inv

array([[ 8.10647933e+16, -1.35107989e+17,  5.40431955e+16],
       [-1.62129587e+17,  2.70215978e+17, -1.08086391e+17],
       [ 8.10647933e+16, -1.35107989e+17,  5.40431955e+16]])

In [175]:
m * m_inv

array([[ 8.10647933e+16, -2.70215978e+17,  1.62129587e+17],
       [-4.86388760e+17,  1.08086391e+18, -5.40431955e+17],
       [ 4.86388760e+17, -9.45755922e+17,  4.32345564e+17]])

In [177]:
np.dot(m, m_inv)

array([[-16., -32.,  16.],
       [ 16., -32.,  16.],
       [  0.,   0.,   0.]])

In [178]:
np.dot(m_inv, m)

array([[  16.,   40.,    0.],
       [  64.,   32., -128.],
       [ -32.,  -16.,   64.]])

In [179]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [180]:
m_inv = np.linalg.inv(m)
m_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [181]:
np.dot(m, m_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [182]:
np.dot(m_inv, m)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [187]:
n = np.array([[1, 3, 5], [2, 6, 6], [5, 7, 9]])
n

array([[1, 3, 5],
       [2, 6, 6],
       [5, 7, 9]])

In [188]:
n_inv = np.linalg.inv(n)
n_inv

array([[-0.375, -0.25 ,  0.375],
       [-0.375,  0.5  , -0.125],
       [ 0.5  , -0.25 ,  0.   ]])

In [189]:
np.dot(n, n_inv)

array([[ 1.00000000e+00,  1.66533454e-16, -5.55111512e-17],
       [-2.22044605e-16,  1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16, -5.55111512e-17,  1.00000000e+00]])

In [186]:
np.dot(n_inv, n)

array([[ 0.4375, -0.6875, -0.3125],
       [ 0.625 ,  0.875 ,  1.125 ],
       [-0.625 ,  0.125 , -0.125 ]])

In [190]:
np.linalg.det(n)

-31.999999999999986

In [193]:
np.linalg.norm(r)

3.7416573867739413

In [192]:
r

array([[1],
       [2],
       [3]])

In [194]:
lst = [1, 2, 3, 4, 5]


In [195]:
lst.index(3)

2

In [196]:
lst1 = [6, 7,8]

In [197]:
lst2 = lst + lst1
lst2

[1, 2, 3, 4, 5, 6, 7, 8]

In [200]:
lst3 = lst.extend([10])
lst3

In [201]:
lst3

In [202]:
lst

[1, 2, 3, 4, 5, 10, 10]

In [203]:
lst.extend(('p', 's'))

In [204]:
lst

[1, 2, 3, 4, 5, 10, 10, 'p', 's']

In [214]:
lst1 = [2, 3, 4, 5, 6, 6, 7]

In [208]:
lst1.insert(10, 1)

In [209]:
lst1

[2, 3, 4, 5, 6, 6, 7, 1, 1]

In [210]:
lst1.insert(1, 10)

In [211]:
lst1

[2, 10, 3, 4, 5, 6, 6, 7, 1, 1]

In [212]:
lst1.insert(3, [33, 44])

In [213]:
lst1

[2, 10, 3, [33, 44], 4, 5, 6, 6, 7, 1, 1]

In [217]:
sorted(lst1, reverse= True)

[7, 6, 6, 5, 4, 3, 2]

In [218]:
names = ['selim hossain', 'rafik al', 'snata islam', 'rahim badsha']

In [219]:
sorted(names, key= lambda x: x.split(' ')[-1])

['rafik al', 'rahim badsha', 'selim hossain', 'snata islam']

In [220]:
lst1

[2, 3, 4, 5, 6, 6, 7]

In [221]:
lst1.remove(5)

In [222]:
lst1

[2, 3, 4, 6, 6, 7]

# set practicing  

In [223]:
x = {1, 2, 3, 4, 3, 2}

In [224]:
x

{1, 2, 3, 4}

In [225]:
type(x)

set

In [226]:
x.add(5)

In [227]:
x

{1, 2, 3, 4, 5}

In [230]:
x.update((6, 7))

In [231]:
x

{1, 2, 3, 4, 5, 6, 7}

In [232]:
x.update([8])

In [233]:
x

{1, 2, 3, 4, 5, 6, 7, 8}

In [236]:
x.update((9, ))

In [237]:
x

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [238]:
x.add((33, 44, 55))

In [239]:
x

{(33, 44, 55), 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [240]:
x.add(10)

In [241]:
x

{(33, 44, 55), 1, 10, 2, 3, 4, 5, 6, 7, 8, 9}

In [242]:
x = {1, 2, 4}
y = {4, 5, 6}

In [243]:
x.union(y)

{1, 2, 4, 5, 6}

In [244]:
x

{1, 2, 4}

In [245]:
x.intersection(y)

{4}

In [246]:
x.difference(y)

{1, 2}

In [247]:
sum(x)

7

In [248]:
dix = {'name' : 'selim hossain', 'car': 'audi', 'profession': 'student'}
dix

{'name': 'selim hossain', 'car': 'audi', 'profession': 'student'}

In [249]:
dix.items

<function dict.items>

In [250]:
dix.items()

dict_items([('name', 'selim hossain'), ('car', 'audi'), ('profession', 'student')])

In [251]:
type(dix.items())

dict_items

In [254]:
for key, val in dix.items():
    print(key,':', val)

name : selim hossain
car : audi
profession : student


In [256]:
dix.values()

dict_values(['selim hossain', 'audi', 'student'])

In [257]:
dix.keys()

dict_keys(['name', 'car', 'profession'])

In [258]:
dix['favourite actor'] = 'salman khan'

In [259]:
dix

{'name': 'selim hossain',
 'car': 'audi',
 'profession': 'student',
 'favourite actor': 'salman khan'}

In [265]:
dix.update({'singer' : ['sohag', 'jagjit', 'pagol maon']})

In [266]:
dix

{'name': 'selim hossain',
 'car': 'audi',
 'profession': 'student',
 'favourite actor': 'salman khan',
 'singer': ['sohag', 'jagjit', 'pagol maon']}

In [267]:
dix.get('singer')

['sohag', 'jagjit', 'pagol maon']

In [268]:
dix['favourite actor']

'salman khan'

In [272]:
dix.popitem()

('singer', ['sohag', 'jagjit', 'pagol maon'])

In [273]:
dix

{'name': 'selim hossain',
 'car': 'audi',
 'profession': 'student',
 'favourite actor': 'salman khan'}

In [274]:
dix.pop('car')

'audi'

In [275]:
dix

{'name': 'selim hossain',
 'profession': 'student',
 'favourite actor': 'salman khan'}

In [276]:
dix['singer'] = ['sohag', 'kajol', 'santa']

In [277]:
dix

{'name': 'selim hossain',
 'profession': 'student',
 'favourite actor': 'salman khan',
 'singer': ['sohag', 'kajol', 'santa']}

In [279]:
dix.popitem()

('singer', ['sohag', 'kajol', 'santa'])

In [283]:
dix['chandra'] = {'mama': {'amar': 'jibon'}}

In [284]:
dix

{'name': 'selim hossain',
 'profession': 'student',
 'favourite actor': 'salman khan',
 'chandra': {'mama': {'amar': 'jibon'}}}

In [286]:
dix['chandra']['mama']['amar']

'jibon'

In [287]:
tup = (1, 3,4,2,2,3)

In [288]:
tup

(1, 3, 4, 2, 2, 3)

In [290]:
tup.count(3)

2

In [297]:
xx = np.arange(1, 51)

In [298]:
yy = np.random.choice(xx, (5, 5))
yy

array([[14, 15, 48,  2, 12],
       [43, 36, 21, 42,  1],
       [21,  3, 25, 12, 24],
       [12, 21, 49,  6, 28],
       [40,  5,  4, 22, 37]])

In [300]:
import pandas as pd

In [301]:
x = pd.Series(xx)
x

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
40    41
41    42
42    43
43    44
44    45
45    46
46    47
47    48
48    49
49    50
dtype: int32

In [303]:
jj = np.random.choice(x, 10)
jj

array([44, 30, 36, 11, 23, 28, 41, 38, 31, 40])

In [304]:
x.sample(10)

1      2
48    49
29    30
15    16
18    19
13    14
23    24
8      9
40    41
2      3
dtype: int32

In [313]:
x.agg([np.mean, 'count'])

mean     25.5
count    50.0
dtype: float64

In [315]:
np.random.sample(10)

array([0.11675279, 0.54295649, 0.34079044, 0.11775506, 0.05255714,
       0.28587932, 0.14266171, 0.13004476, 0.86302196, 0.80559117])