In [7]:
import numpy as np

a = np.array([[1,2,3,8],[2,3,4,2],[4,5,6,7]])
a.dtype

dtype('int32')

In [8]:
a.strides

(16, 4)

In [17]:
a.ravel().view()

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 3, 0,
       0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0, 0, 0,
       7, 0, 0, 0], dtype=uint8)

In [22]:
b = a.ravel().view(dtype= np.uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 2, 0, 0, 0, 3, 0,
       0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0, 6, 0, 0, 0,
       7, 0, 0, 0], dtype=uint8)

In [23]:
b.strides

(1,)

In [74]:
y = np.array(np.random.randint(low= 0, high= 100, size= (5, 5)))
y

array([[10, 20, 52, 92, 44],
       [92, 99,  5, 12, 98],
       [71, 26, 48, 50, 85],
       [44, 61, 22, 37,  9],
       [52, 25, 72, 39, 20]])

In [34]:
y[[0,1,2,3],[1,2,3,4]]

array([26, 38, 30, 25])

In [41]:
xx = np.where(y % 2 == 0, y, "selim")
xx

array([['28', '26', '36', '48', 'selim'],
       ['selim', '44', '38', '34', '36'],
       ['selim', '10', '36', '30', 'selim'],
       ['selim', 'selim', '30', '28', 'selim'],
       ['22', '18', '30', '34', '32']], dtype='<U11')

In [42]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [45]:
y

array([[9, 6, 4, 0, 7],
       [2, 7, 1, 5, 3],
       [6, 2, 8, 7, 2],
       [7, 9, 7, 6, 2],
       [6, 4, 0, 2, 8]])

In [55]:
mask = y.argmin()
mask

3

In [57]:
p = y.ravel()

In [58]:
p[mask]

0

In [53]:
r = np.sum(y,axis=0)
r.shape

(5,)

In [50]:
rr = np.sum(y, axis= 1)

In [52]:
rr.shape

(5,)

In [75]:
ran = np.random.randint(0,100,size=(5,4))
ran

array([[80, 89, 88, 36],
       [90, 58,  1,  4],
       [88, 97, 37, 24],
       [80, 20, 83, 35],
       [55, 96, 69, 72]])

In [81]:
pp

array([4, 3, 1, 1], dtype=int64)

In [76]:
pp = ran.argmin(axis= 0)
pp

array([4, 3, 1, 1], dtype=int64)

In [78]:
pp.argsort()

array([2, 3, 1, 0], dtype=int64)

In [80]:
pp[[2, 3, 1, 0]]

array([1, 1, 3, 4], dtype=int64)

In [70]:
y

array([[9, 6, 4, 0, 7],
       [2, 7, 1, 5, 3],
       [6, 2, 8, 7, 2],
       [7, 9, 7, 6, 2],
       [6, 4, 0, 2, 8]])

In [71]:
j = np.var(a, axis= 0)
j

array([1.55555556, 1.55555556, 1.55555556, 6.88888889])

In [73]:
j

array([1.55555556, 1.55555556, 1.55555556, 6.88888889])

In [72]:
jjj = j.argmin()
jjj

0

In [89]:
aa = np.random.random(size= 50).reshape(5,10)
aa

array([[0.36172796, 0.17579225, 0.95941174, 0.08085891, 0.32227421,
        0.37886158, 0.34094386, 0.81890219, 0.87996864, 0.74196274],
       [0.07577395, 0.50437934, 0.82747566, 0.24083929, 0.91147271,
        0.95597157, 0.57169483, 0.99421557, 0.13128902, 0.17161154],
       [0.63812817, 0.16564675, 0.52068005, 0.81060605, 0.2883086 ,
        0.22938611, 0.00176593, 0.62343445, 0.33106659, 0.94778788],
       [0.49937287, 0.46124638, 0.78188332, 0.69140692, 0.85963367,
        0.65878956, 0.80103441, 0.71571549, 0.73932861, 0.75242244],
       [0.25724347, 0.65498065, 0.29594857, 0.89420023, 0.61209126,
        0.17048205, 0.53711035, 0.90681039, 0.09859555, 0.44604269]])

In [90]:
variance = np.var(aa, axis= 1)
variance

array([0.08867803, 0.12099861, 0.08187044, 0.01458108, 0.07304358])

In [92]:
sr = np.argsort(variance)
sr

array([3, 4, 2, 0, 1], dtype=int64)

In [93]:
aa[sr]

array([[0.49937287, 0.46124638, 0.78188332, 0.69140692, 0.85963367,
        0.65878956, 0.80103441, 0.71571549, 0.73932861, 0.75242244],
       [0.25724347, 0.65498065, 0.29594857, 0.89420023, 0.61209126,
        0.17048205, 0.53711035, 0.90681039, 0.09859555, 0.44604269],
       [0.63812817, 0.16564675, 0.52068005, 0.81060605, 0.2883086 ,
        0.22938611, 0.00176593, 0.62343445, 0.33106659, 0.94778788],
       [0.36172796, 0.17579225, 0.95941174, 0.08085891, 0.32227421,
        0.37886158, 0.34094386, 0.81890219, 0.87996864, 0.74196274],
       [0.07577395, 0.50437934, 0.82747566, 0.24083929, 0.91147271,
        0.95597157, 0.57169483, 0.99421557, 0.13128902, 0.17161154]])

In [94]:
aa

array([[0.36172796, 0.17579225, 0.95941174, 0.08085891, 0.32227421,
        0.37886158, 0.34094386, 0.81890219, 0.87996864, 0.74196274],
       [0.07577395, 0.50437934, 0.82747566, 0.24083929, 0.91147271,
        0.95597157, 0.57169483, 0.99421557, 0.13128902, 0.17161154],
       [0.63812817, 0.16564675, 0.52068005, 0.81060605, 0.2883086 ,
        0.22938611, 0.00176593, 0.62343445, 0.33106659, 0.94778788],
       [0.49937287, 0.46124638, 0.78188332, 0.69140692, 0.85963367,
        0.65878956, 0.80103441, 0.71571549, 0.73932861, 0.75242244],
       [0.25724347, 0.65498065, 0.29594857, 0.89420023, 0.61209126,
        0.17048205, 0.53711035, 0.90681039, 0.09859555, 0.44604269]])

In [96]:
y

array([[10, 20, 52, 92, 44],
       [92, 99,  5, 12, 98],
       [71, 26, 48, 50, 85],
       [44, 61, 22, 37,  9],
       [52, 25, 72, 39, 20]])

In [97]:
y[[2,4]]

array([[71, 26, 48, 50, 85],
       [52, 25, 72, 39, 20]])

In [98]:
y

array([[10, 20, 52, 92, 44],
       [92, 99,  5, 12, 98],
       [71, 26, 48, 50, 85],
       [44, 61, 22, 37,  9],
       [52, 25, 72, 39, 20]])

In [99]:
y[-3:]

array([[71, 26, 48, 50, 85],
       [44, 61, 22, 37,  9],
       [52, 25, 72, 39, 20]])