In [1]:
pip show numpy

Name: numpy
Version: 1.16.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: tables, statsmodels, seaborn, scikit-learn, PyWavelets, pytest-doctestplus, pytest-arraydiff, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, h5py, Bottleneck, bokeh, bkcharts, astropy
Note: you may need to restart the kernel to use updated packages.


In [2]:
pip show scipy

Name: scipy
Version: 1.3.1
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: None
Author-email: None
License: BSD
Location: c:\programdata\anaconda3\lib\site-packages
Requires: 
Required-by: statsmodels, seaborn, scikit-learn
Note: you may need to restart the kernel to use updated packages.


In [3]:
g = list(range(1000000))
%timeit sum(g)

28.2 ms ± 499 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(np.shape(a))
print(np.ndim(a))

(4,)
1


In [11]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
mask1 = [0, 3, 4]
mask2 = [4, 1, 2]

arr[mask1, mask2]

array([ 4, 16, 22])

In [14]:
arr[np.arange(5), np.arange(5)]

array([ 0,  6, 12, 18, 24])

In [15]:
len(arr)

5

In [16]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
len(a)

3

In [18]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr[[0, 2, -1], 1]

array([ 1, 11, 21])

In [23]:
p = np.array(np.arange(12))
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
sub = p[[0,3,7,11]]
sub

array([ 0,  3,  7, 11])

In [27]:
mask = p >5

p[mask]


array([ 6,  7,  8,  9, 10, 11])

In [28]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ab = a[np.arange(0,4), np.arange(1,5)]
ab

array([ 1,  7, 13, 19])

In [30]:
mask = (a % 3 ==0)
mask

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [31]:
a[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [32]:
a[a % 3]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [ 0,  1,  2,  3,  4]]])

In [33]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
out = np.empty_like(a)
out

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
out.fill(0)
out

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
out[mask] = a[mask]
out

array([[ 0,  0,  0,  3,  0],
       [ 0,  6,  0,  0,  9],
       [ 0,  0, 12,  0,  0],
       [15,  0,  0, 18,  0],
       [ 0, 21,  0,  0, 24]])

In [46]:
out

array([[ 0,  0,  0,  3,  0],
       [ 0,  6,  0,  0,  9],
       [ 0,  0, 12,  0,  0],
       [15,  0,  0, 18,  0],
       [ 0, 21,  0,  0, 24]])

In [41]:
np.where(a % 3 == 0, a, 0)

array([[ 0,  0,  0,  3,  0],
       [ 0,  6,  0,  0,  9],
       [ 0,  0, 12,  0,  0],
       [15,  0,  0, 18,  0],
       [ 0, 21,  0,  0, 24]])

In [48]:
mul = np.ndarray(shape= (3, 4))
mul.shape

(3, 4)

In [50]:
num = np.arange(-15, 15).reshape(5, 6) ** 2
num

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [51]:
maxx = np.max(num, axis= 1)
maxx

array([225,  81,   9,  64, 196], dtype=int32)

In [52]:
mayy = np.max(num, axis= 0)
mayy

array([225, 196, 169, 144, 169, 196], dtype=int32)

In [55]:
num

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]], dtype=int32)

In [68]:
np.min(num, axis= 1)


array([100,  16,   0,   9,  81], dtype=int32)

In [69]:
np.argmin(np.min(num, axis= 1))

2

In [70]:
num[2]

array([9, 4, 1, 0, 1, 4], dtype=int32)

In [63]:
d = num.argmin()
d

15

In [72]:
num.shape[1]

6