In [1]:
import numpy as np

In [9]:
a = np.array([[1, 2, 3, 4], [10, 11, 12, 13]])
b = np.array([[5, 6, 7, 8], [21, 22, 23, 24]])

In [19]:
for i, j in zip(a, b):
    print(i,'    ', j)

[1 2 3 4]      [5 6 7 8]
[10 11 12 13]      [21 22 23 24]


In [57]:
[i + j for i, j in zip(a, b)]

[array([ 6,  8, 10, 12]), array([31, 33, 35, 37])]

In [58]:
L= [i + j for i, j in zip(a, b)]

In [60]:
len(L)

2

In [12]:
[1, 2, 3, 4] + [5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]

In [74]:
[(i + j) for i, j in zip(a, b)]

[array([ 6,  8, 10, 12]), array([31, 33, 35, 37])]

In [62]:
sum([(i + j) for i, j in zip(a, b)])


array([37, 41, 45, 49])

In [18]:
sum([1, 2, 3, 4] + [5, 6, 7, 8])

36

In [20]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
df = sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
observed = pd.crosstab(index = df.sex, columns = df.smoker)
observed

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [23]:
type(observed)

pandas.core.frame.DataFrame

In [24]:
obs = observed.to_numpy()

In [38]:
obs.ndim

2

In [26]:
import scipy.stats as stats


In [29]:
chi = stats.chi2_contingency(obs)

In [37]:
chi

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [30]:
chi[3]

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [31]:
expected = chi[3]

In [45]:
xx = np.array([[26, 13, 5], [20, 29, 7]], dtype= np.int64)
xx


array([[26, 13,  5],
       [20, 29,  7]], dtype=int64)

In [44]:
xx.dtype

dtype('int32')

In [46]:
stats.chi2_contingency(xx)

(5.855499314350247, 0.05351733509077522, 2, array([[20.24, 18.48,  5.28],
        [25.76, 23.52,  6.72]]))

In [40]:
j = pd.DataFrame({
    'rep' : [26, 20], 
    'dem' : [13, 29], 
    'other': [5, 7]
    
}, index= ['male', 'female'])
j

rep  dem  other
male     26   13      5
female   20   29      7

In [41]:
stats.chi2_contingency(j)

(5.855499314350247, 0.05351733509077522, 2, array([[20.24, 18.48,  5.28],
        [25.76, 23.52,  6.72]]))

In [42]:
j.to_numpy()

array([[26, 13,  5],
       [20, 29,  7]], dtype=int64)

In [49]:
r = np.array([22, 24, 38, 30, 46, 44], dtype= np.int64)
r

array([22, 24, 38, 30, 46, 44], dtype=int64)

In [50]:
stats.chi2_contingency(r)

(0.0, 1.0, 0, array([22., 24., 38., 30., 46., 44.]))

In [51]:
j.shape

(2, 3)

In [52]:
observed.shape

(2, 2)

In [53]:
row, col = obs.shape

In [54]:
row

2

In [55]:
col

2

In [56]:
observed

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [63]:
obs


array([[60, 97],
       [33, 54]], dtype=int64)

In [64]:
observed

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [65]:
expected

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

$$ X^2 = sum(o-e)^2/e$$

In [72]:
c= sum([(o - e)**2 /e for o, e in zip(obs, expected)])

In [73]:
c[0] + c[1]

0.001934818536627623

In [69]:
c

array([1, 2, 3])

In [71]:
c[0]

1

In [75]:
sum(c)

0.001934818536627623

In [76]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [90]:
observ = pd.crosstab(index= df.sex, columns= df.smoker)
observe = observ.to_numpy()

In [91]:
observe

array([[60, 97],
       [33, 54]], dtype=int64)

In [84]:
expected = stats.chi2_contingency(observed= observ)[3]
expected

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [95]:
sum(sum([(obs - expec)**2 / expec for obs, expec in zip(observe, expected)]))

0.001934818536627623

In [96]:
chi_sq2_test = sum(sum([(obs - expec)**2 / expec for obs, expec in zip(observe, expected)]))

In [99]:
row, col = observe.shape
dof = (col - 1) * (row - 1)

In [104]:
p_value= 1 - stats.chi2.cdf(x= chi_sq2_test, df= dof)

In [105]:
p_value

0.964915107315732

In [106]:
critical_value = stats.chi2.ppf(q = 1-0.05, df = dof)

In [107]:
critical_value

3.841458820694124

In [108]:
if chi_sq2_test >= critical_value:
    print('reject null hypothesis')
else:
    print('fail to reject null hypothesis')

fail to reject null hypothesis


In [109]:
alpha = 0.05
if p_value <= alpha:
    print('reject null hypothesis')

else:
    print('fail to reject null hypothesis')
    

fail to reject null hypothesis


In [111]:
x = [1,2,3,4,5,6]
new_x = [i*2 if i%2 == 0 else -i for i in x]
new_x

[-1, 4, -3, 8, -5, 12]